Algoritmo "ex1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral 
// Descrição   : soma de valores (função)
// Autor(a)    : Odair José
// Data atual  : 29/03/2022
Var
// Seção de Declarações das variáveis 
x,y: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Digite o primeiro número:")
   leia(x)
   escreval ("Digite o segundo número:")
   leia(y)
   escreva ("A soma dos números é:",x+y)

Fimalgoritmo
